---
swagger: "2.0"
info:
  description: "This is the book store built for Hypermedia course at Polimi."
  version: "1.0.0"
  title: "Libreggiamo"
  contact:
    email: "alberto.frattini@mail.polimi.it"
  license:
    name: "Apache-2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/v2"
tags:
- name: "book"
  description: "Available book"
- name: "author"
  description: "Author of some book"
- name: "event"
  description: "Event in which some book is presented"
schemes:
- "http"
paths:
  /books:
    get:
      tags:
      - "book"
      summary: "Books available in the inventory"
      description: "List of books available in the inventory"
      operationId: "getAllBooks"
      produces:
      - "applications/json"
      parameters:
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0"
        required: false
        type: "integer"
      - name: "limit"
        in: "query"
        description: "Maximum number of items per page. Default is 20 and \
          \ cannot exceed 500."
        required: false
        type: "integer"
      responses:
        200:
          description: "A collection of Books"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /books/filter:
    get:
      tags:
      - "book"
      summary: "Books available in the inventory"
      description: "List of books available in the inventory"
      operationId: "getBooksThroughFilter"
      produces:
      - "applications/json"
      parameters:
      - name: "titleOrAuthor"
        in: "query"
        description: "Title or Author of the book"
        required: false
        type: "string"
      - name: "genre"
        in: "query"
        description: "Book genre"
        required: false
        type: "string"
      - name: "theme"
        in: "query"
        description: "Book theme"
        required: false
        type: "string"
      responses:
        200:
          description: "A collection of Books"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /books/{bookIsbn}:
    get:
      tags:
      - "book"
      summary: "Find book by ID"
      description: "Returns a book"
      operationId: "getBookByIsbn"
      produces:
      - "application/json"
      parameters:
      - name: "bookIsbn"
        in: "path"
        description: "ID of book to return"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Book"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Book not found"
      x-swagger-router-controller: "Book"
  /books/similar/{bookIsbn}:
    get:
      tags:
      - "book"
      summary: "Find similar books by Isbn"
      description: "Returns similar books to the one in the path"
      operationId: "getBooksBySimilarity"
      produces:
      - "application/json"
      parameters:
      - name: "bookIsbn"
        in: "path"
        description: "ID of book to return"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Book"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Books not found"
      x-swagger-router-controller: "Book"
  /books/reviews/{bookIsbn}:
    get:
      tags:
      - "book"
      summary: "Find book's reviews by Isbn"
      description: "Returns book's reviews"
      operationId: "getReviewsOfBook"
      produces:
      - "application/json"
      parameters:
      - name: "bookIsbn"
        in: "path"
        description: "Isbn of book's reviews to return"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Book"
        400:
          description: "Invalid Isbn supplied"
        404:
          description: "Reviews not found"
      x-swagger-router-controller: "Book"
  /events:
    get:
      tags:
      - "event"
      summary: "Events available"
      description: "List of all events"
      operationId: "getAllEvents"
      produces:
      - "applications/json"
      responses:
        200:
          description: "A collection of events"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /events/{eventId}:
    get:
      tags:
      - "event"
      summary: "Find event by ID"
      description: "Returns an event"
      operationId: "getEventById"
      produces:
      - "application/json"
      parameters:
      - name: "eventId"
        in: "path"
        description: "ID of event to return"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Event"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Book not found"
      x-swagger-router-controller: "Book"
  /events/filter:
    get:
      tags:
      - "event"
      summary: "Find events by month"
      description: "Returns events of the specified month"
      operationId: "getEventsByMonth"
      produces:
      - "application/json"
      parameters:
      - name: "month"
        in: "query"
        description: "Month of the events"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Event"
        400:
          description: "Invalid month supplied"
        404:
          description: "Events not found"
      x-swagger-router-controller: "Book"
  /authors/{authorId}:
    get:
      tags:
      - "author"
      summary: "Find author by ID"
      description: "Returns an author"
      operationId: "getAuthorById"
      produces:
      - "application/json"
      parameters:
      - name: "authorId"
        in: "path"
        description: "ID of author to return"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Author"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Author not found"
      x-swagger-router-controller: "Book"
  /users/login:
    post:
      tags:
      - "user"
      summary: "Login"
      description: "Login of a user"
      operationId: "signInUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "formData"
        required: true
        type: "string"
      - name: "password"
        in: "formData"
        required: true
        type: "string"
      responses:
        200:
          description: "succesfull login"
        404:
          description: "unauthorized"
      x-swagger-router-controller: "User"
  /users/signUp:
    post:
      tags:
      - "user"
      summary: "SignUp"
      description: "SignUp of a user"
      operationId: "signUpUser"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "formData"
        required: true
        type: "string"
      - name: "email"
        in: "formData"
        required: true
        type: "string"
      - name: "password"
        in: "formData"
        required: true
        type: "string"
      responses:
        200:
          description: "succesfull login"
        404:
          description: "unauthorized"
      x-swagger-router-controller: "User"
definitions:
  Book:
    type: "object"
    required:
    - "ISBN"
    - "title"
    - "price"
    properties:
      ISBN:
        type: "string"
      title:
        type: "string"
      genre:
        type: "string"
      theme:
        type: "string"
      publisher:
        type: "string"
      description:
        type: "string"
      price:
        type: "number"
        format: "float"
        minimum: 0.01
        maximum: 100000000000000
      coverUrl:
        type: "string"
      status:
        type: "string"
        description: "Book availability in the inventory"
        enum:
        - "available"
        - "out of stock"
    title: "Book"
    description: "A book for sale in the store"
    example:
      id: 0
      title: "Il deserto dei tartari"
      author: "Dino Buzzati"
      price: 7.1
      status: "available"
  Event:
    type: "object"
    required:
    - "eventName"
    - "bookPresented"
    properties:
      eventName:
        type: "string"
      bookPresented:
        type: "string"
      eventLocation:
        type: "string"
      eventDate:
        type: "string"
      imageUrl:
        type: "string"
    title: "Event"
    description: "An event scheduled in which a book will be presented"
    example:
      eventName: "The tartar steppe presentation"
      bookPresented: "The tartar steppe"
      eventLocation: "Feltrinelli"
      eventDate: "2019-06-20"
  Author:
    type: "object"
    required:
    - "authorName"
    properties:
      authorName:
        type: "string"
      authorBiography:
        type: "string"
      profileUlr:
        type: "string"
    title: "Author"
    description: "An author of some book in the store"
    example:
      authorName: "Michael Connelly"
      authorBiography: "Michael Connelly was born in..."
  User:
    type: "object"
    required:
    - "name"
    - "email"
    - "password"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
    title: "User"
    description: "A user of the book store."
    example:
      name: "Mario Rossi"
      email: "example@example.com"
      password: "****"












